// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calcCE
double calcCE(double xmax, double ymax, NumericVector x, NumericVector y);
RcppExport SEXP _EmpiricalPatternR_calcCE(SEXP xmaxSEXP, SEXP ymaxSEXP, SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type xmax(xmaxSEXP);
    Rcpp::traits::input_parameter< double >::type ymax(ymaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(calcCE(xmax, ymax, x, y));
    return rcpp_result_gen;
END_RCPP
}
// calcEnergy
double calcEnergy(double CEcurrent, double CEtarget);
RcppExport SEXP _EmpiricalPatternR_calcEnergy(SEXP CEcurrentSEXP, SEXP CEtargetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type CEcurrent(CEcurrentSEXP);
    Rcpp::traits::input_parameter< double >::type CEtarget(CEtargetSEXP);
    rcpp_result_gen = Rcpp::wrap(calcEnergy(CEcurrent, CEtarget));
    return rcpp_result_gen;
END_RCPP
}
// estimateWeibullParams
List estimateWeibullParams(NumericVector x);
RcppExport SEXP _EmpiricalPatternR_estimateWeibullParams(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(estimateWeibullParams(x));
    return rcpp_result_gen;
END_RCPP
}
// calcWeibullKS
double calcWeibullKS(NumericVector x, double shape, double scale, double location);
RcppExport SEXP _EmpiricalPatternR_calcWeibullKS(SEXP xSEXP, SEXP shapeSEXP, SEXP scaleSEXP, SEXP locationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< double >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< double >::type location(locationSEXP);
    rcpp_result_gen = Rcpp::wrap(calcWeibullKS(x, shape, scale, location));
    return rcpp_result_gen;
END_RCPP
}
// calcWeibullEnergy
double calcWeibullEnergy(NumericVector x, double targetShape, double targetScale, double targetLocation);
RcppExport SEXP _EmpiricalPatternR_calcWeibullEnergy(SEXP xSEXP, SEXP targetShapeSEXP, SEXP targetScaleSEXP, SEXP targetLocationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type targetShape(targetShapeSEXP);
    Rcpp::traits::input_parameter< double >::type targetScale(targetScaleSEXP);
    Rcpp::traits::input_parameter< double >::type targetLocation(targetLocationSEXP);
    rcpp_result_gen = Rcpp::wrap(calcWeibullEnergy(x, targetShape, targetScale, targetLocation));
    return rcpp_result_gen;
END_RCPP
}
// calcCanopyCoverCpp
double calcCanopyCoverCpp(NumericVector x, NumericVector y, NumericVector crown_radius, double plot_size, double grid_res);
RcppExport SEXP _EmpiricalPatternR_calcCanopyCoverCpp(SEXP xSEXP, SEXP ySEXP, SEXP crown_radiusSEXP, SEXP plot_sizeSEXP, SEXP grid_resSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type crown_radius(crown_radiusSEXP);
    Rcpp::traits::input_parameter< double >::type plot_size(plot_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type grid_res(grid_resSEXP);
    rcpp_result_gen = Rcpp::wrap(calcCanopyCoverCpp(x, y, crown_radius, plot_size, grid_res));
    return rcpp_result_gen;
END_RCPP
}
// calcNearestDistanceCpp
NumericVector calcNearestDistanceCpp(NumericVector x1, NumericVector y1, NumericVector x2, NumericVector y2);
RcppExport SEXP _EmpiricalPatternR_calcNearestDistanceCpp(SEXP x1SEXP, SEXP y1SEXP, SEXP x2SEXP, SEXP y2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y2(y2SEXP);
    rcpp_result_gen = Rcpp::wrap(calcNearestDistanceCpp(x1, y1, x2, y2));
    return rcpp_result_gen;
END_RCPP
}
// calcCrownRadiusCpp
NumericVector calcCrownRadiusCpp(NumericVector dbh, IntegerVector species_idx, NumericMatrix params);
RcppExport SEXP _EmpiricalPatternR_calcCrownRadiusCpp(SEXP dbhSEXP, SEXP species_idxSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dbh(dbhSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type species_idx(species_idxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(calcCrownRadiusCpp(dbh, species_idx, params));
    return rcpp_result_gen;
END_RCPP
}
// calcHeightCpp
NumericVector calcHeightCpp(NumericVector dbh, IntegerVector species_idx, NumericMatrix params);
RcppExport SEXP _EmpiricalPatternR_calcHeightCpp(SEXP dbhSEXP, SEXP species_idxSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dbh(dbhSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type species_idx(species_idxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(calcHeightCpp(dbh, species_idx, params));
    return rcpp_result_gen;
END_RCPP
}
// calcCrownBaseHeightCpp
NumericVector calcCrownBaseHeightCpp(NumericVector dbh, NumericVector height, IntegerVector species_idx, NumericMatrix params);
RcppExport SEXP _EmpiricalPatternR_calcCrownBaseHeightCpp(SEXP dbhSEXP, SEXP heightSEXP, SEXP species_idxSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dbh(dbhSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type height(heightSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type species_idx(species_idxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(calcCrownBaseHeightCpp(dbh, height, species_idx, params));
    return rcpp_result_gen;
END_RCPP
}
// calcCrownOverlapCpp
double calcCrownOverlapCpp(NumericVector x, NumericVector y, NumericVector crown_radius);
RcppExport SEXP _EmpiricalPatternR_calcCrownOverlapCpp(SEXP xSEXP, SEXP ySEXP, SEXP crown_radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type crown_radius(crown_radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(calcCrownOverlapCpp(x, y, crown_radius));
    return rcpp_result_gen;
END_RCPP
}
// calcDistributionEnergy
double calcDistributionEnergy(NumericVector values, NumericVector targets, NumericVector weights);
RcppExport SEXP _EmpiricalPatternR_calcDistributionEnergy(SEXP valuesSEXP, SEXP targetsSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type targets(targetsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(calcDistributionEnergy(values, targets, weights));
    return rcpp_result_gen;
END_RCPP
}
// calcCanopyCoverIndexedCpp
double calcCanopyCoverIndexedCpp(NumericVector x, NumericVector y, NumericVector crown_radius, double plot_size, double grid_res);
RcppExport SEXP _EmpiricalPatternR_calcCanopyCoverIndexedCpp(SEXP xSEXP, SEXP ySEXP, SEXP crown_radiusSEXP, SEXP plot_sizeSEXP, SEXP grid_resSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type crown_radius(crown_radiusSEXP);
    Rcpp::traits::input_parameter< double >::type plot_size(plot_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type grid_res(grid_resSEXP);
    rcpp_result_gen = Rcpp::wrap(calcCanopyCoverIndexedCpp(x, y, crown_radius, plot_size, grid_res));
    return rcpp_result_gen;
END_RCPP
}
// calcEnergyComponentsCpp
List calcEnergyComponentsCpp(NumericVector metrics, NumericVector targets, NumericVector weights, IntegerVector component_ids);
RcppExport SEXP _EmpiricalPatternR_calcEnergyComponentsCpp(SEXP metricsSEXP, SEXP targetsSEXP, SEXP weightsSEXP, SEXP component_idsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type metrics(metricsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type targets(targetsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type component_ids(component_idsSEXP);
    rcpp_result_gen = Rcpp::wrap(calcEnergyComponentsCpp(metrics, targets, weights, component_ids));
    return rcpp_result_gen;
END_RCPP
}
// calcCanopyCoverParallel
double calcCanopyCoverParallel(NumericVector x, NumericVector y, NumericVector crown_radius, double plot_size, double grid_res, int n_threads);
RcppExport SEXP _EmpiricalPatternR_calcCanopyCoverParallel(SEXP xSEXP, SEXP ySEXP, SEXP crown_radiusSEXP, SEXP plot_sizeSEXP, SEXP grid_resSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type crown_radius(crown_radiusSEXP);
    Rcpp::traits::input_parameter< double >::type plot_size(plot_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type grid_res(grid_resSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(calcCanopyCoverParallel(x, y, crown_radius, plot_size, grid_res, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// calcNearestDistanceParallel
NumericVector calcNearestDistanceParallel(NumericVector x1, NumericVector y1, NumericVector x2, NumericVector y2, int n_threads);
RcppExport SEXP _EmpiricalPatternR_calcNearestDistanceParallel(SEXP x1SEXP, SEXP y1SEXP, SEXP x2SEXP, SEXP y2SEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y2(y2SEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(calcNearestDistanceParallel(x1, y1, x2, y2, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// calcCrownRadiusParallel
NumericVector calcCrownRadiusParallel(NumericVector dbh, IntegerVector species_idx, NumericMatrix params, int n_threads);
RcppExport SEXP _EmpiricalPatternR_calcCrownRadiusParallel(SEXP dbhSEXP, SEXP species_idxSEXP, SEXP paramsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dbh(dbhSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type species_idx(species_idxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(calcCrownRadiusParallel(dbh, species_idx, params, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// calcHeightParallel
NumericVector calcHeightParallel(NumericVector dbh, IntegerVector species_idx, NumericMatrix params, int n_threads);
RcppExport SEXP _EmpiricalPatternR_calcHeightParallel(SEXP dbhSEXP, SEXP species_idxSEXP, SEXP paramsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dbh(dbhSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type species_idx(species_idxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(calcHeightParallel(dbh, species_idx, params, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// calcCrownBaseHeightParallel
NumericVector calcCrownBaseHeightParallel(NumericVector dbh, NumericVector height, IntegerVector species_idx, NumericMatrix params, int n_threads);
RcppExport SEXP _EmpiricalPatternR_calcCrownBaseHeightParallel(SEXP dbhSEXP, SEXP heightSEXP, SEXP species_idxSEXP, SEXP paramsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dbh(dbhSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type height(heightSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type species_idx(species_idxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(calcCrownBaseHeightParallel(dbh, height, species_idx, params, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// calcCEParallel
double calcCEParallel(double xmax, double ymax, NumericVector x, NumericVector y, int n_threads);
RcppExport SEXP _EmpiricalPatternR_calcCEParallel(SEXP xmaxSEXP, SEXP ymaxSEXP, SEXP xSEXP, SEXP ySEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type xmax(xmaxSEXP);
    Rcpp::traits::input_parameter< double >::type ymax(ymaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(calcCEParallel(xmax, ymax, x, y, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// getOpenMPInfo
List getOpenMPInfo();
RcppExport SEXP _EmpiricalPatternR_getOpenMPInfo() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(getOpenMPInfo());
    return rcpp_result_gen;
END_RCPP
}
// calcCanopyCoverHybrid
double calcCanopyCoverHybrid(NumericVector x, NumericVector y, NumericVector crown_radius, double plot_size, double grid_res, int n_threads);
RcppExport SEXP _EmpiricalPatternR_calcCanopyCoverHybrid(SEXP xSEXP, SEXP ySEXP, SEXP crown_radiusSEXP, SEXP plot_sizeSEXP, SEXP grid_resSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type crown_radius(crown_radiusSEXP);
    Rcpp::traits::input_parameter< double >::type plot_size(plot_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type grid_res(grid_resSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(calcCanopyCoverHybrid(x, y, crown_radius, plot_size, grid_res, n_threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_EmpiricalPatternR_calcCE", (DL_FUNC) &_EmpiricalPatternR_calcCE, 4},
    {"_EmpiricalPatternR_calcEnergy", (DL_FUNC) &_EmpiricalPatternR_calcEnergy, 2},
    {"_EmpiricalPatternR_estimateWeibullParams", (DL_FUNC) &_EmpiricalPatternR_estimateWeibullParams, 1},
    {"_EmpiricalPatternR_calcWeibullKS", (DL_FUNC) &_EmpiricalPatternR_calcWeibullKS, 4},
    {"_EmpiricalPatternR_calcWeibullEnergy", (DL_FUNC) &_EmpiricalPatternR_calcWeibullEnergy, 4},
    {"_EmpiricalPatternR_calcCanopyCoverCpp", (DL_FUNC) &_EmpiricalPatternR_calcCanopyCoverCpp, 5},
    {"_EmpiricalPatternR_calcNearestDistanceCpp", (DL_FUNC) &_EmpiricalPatternR_calcNearestDistanceCpp, 4},
    {"_EmpiricalPatternR_calcCrownRadiusCpp", (DL_FUNC) &_EmpiricalPatternR_calcCrownRadiusCpp, 3},
    {"_EmpiricalPatternR_calcHeightCpp", (DL_FUNC) &_EmpiricalPatternR_calcHeightCpp, 3},
    {"_EmpiricalPatternR_calcCrownBaseHeightCpp", (DL_FUNC) &_EmpiricalPatternR_calcCrownBaseHeightCpp, 4},
    {"_EmpiricalPatternR_calcCrownOverlapCpp", (DL_FUNC) &_EmpiricalPatternR_calcCrownOverlapCpp, 3},
    {"_EmpiricalPatternR_calcDistributionEnergy", (DL_FUNC) &_EmpiricalPatternR_calcDistributionEnergy, 3},
    {"_EmpiricalPatternR_calcCanopyCoverIndexedCpp", (DL_FUNC) &_EmpiricalPatternR_calcCanopyCoverIndexedCpp, 5},
    {"_EmpiricalPatternR_calcEnergyComponentsCpp", (DL_FUNC) &_EmpiricalPatternR_calcEnergyComponentsCpp, 4},
    {"_EmpiricalPatternR_calcCanopyCoverParallel", (DL_FUNC) &_EmpiricalPatternR_calcCanopyCoverParallel, 6},
    {"_EmpiricalPatternR_calcNearestDistanceParallel", (DL_FUNC) &_EmpiricalPatternR_calcNearestDistanceParallel, 5},
    {"_EmpiricalPatternR_calcCrownRadiusParallel", (DL_FUNC) &_EmpiricalPatternR_calcCrownRadiusParallel, 4},
    {"_EmpiricalPatternR_calcHeightParallel", (DL_FUNC) &_EmpiricalPatternR_calcHeightParallel, 4},
    {"_EmpiricalPatternR_calcCrownBaseHeightParallel", (DL_FUNC) &_EmpiricalPatternR_calcCrownBaseHeightParallel, 5},
    {"_EmpiricalPatternR_calcCEParallel", (DL_FUNC) &_EmpiricalPatternR_calcCEParallel, 5},
    {"_EmpiricalPatternR_getOpenMPInfo", (DL_FUNC) &_EmpiricalPatternR_getOpenMPInfo, 0},
    {"_EmpiricalPatternR_calcCanopyCoverHybrid", (DL_FUNC) &_EmpiricalPatternR_calcCanopyCoverHybrid, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_EmpiricalPatternR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
