# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcCE <- function(xmax, ymax, x, y) {
    .Call(`_EmpiricalPatternR_calcCE`, xmax, ymax, x, y)
}

calcEnergy <- function(CEcurrent, CEtarget) {
    .Call(`_EmpiricalPatternR_calcEnergy`, CEcurrent, CEtarget)
}

estimateWeibullParams <- function(x) {
    .Call(`_EmpiricalPatternR_estimateWeibullParams`, x)
}

calcWeibullKS <- function(x, shape, scale, location) {
    .Call(`_EmpiricalPatternR_calcWeibullKS`, x, shape, scale, location)
}

calcWeibullEnergy <- function(x, targetShape, targetScale, targetLocation) {
    .Call(`_EmpiricalPatternR_calcWeibullEnergy`, x, targetShape, targetScale, targetLocation)
}

calcCanopyCoverCpp <- function(x, y, crown_radius, plot_size = 100.0, grid_res = 0.5) {
    .Call(`_EmpiricalPatternR_calcCanopyCoverCpp`, x, y, crown_radius, plot_size, grid_res)
}

calcNearestDistanceCpp <- function(x1, y1, x2, y2) {
    .Call(`_EmpiricalPatternR_calcNearestDistanceCpp`, x1, y1, x2, y2)
}

calcCrownRadiusCpp <- function(dbh, species_idx, params) {
    .Call(`_EmpiricalPatternR_calcCrownRadiusCpp`, dbh, species_idx, params)
}

calcHeightCpp <- function(dbh, species_idx, params) {
    .Call(`_EmpiricalPatternR_calcHeightCpp`, dbh, species_idx, params)
}

calcCrownBaseHeightCpp <- function(dbh, height, species_idx, params) {
    .Call(`_EmpiricalPatternR_calcCrownBaseHeightCpp`, dbh, height, species_idx, params)
}

calcCrownOverlapCpp <- function(x, y, crown_radius) {
    .Call(`_EmpiricalPatternR_calcCrownOverlapCpp`, x, y, crown_radius)
}

calcDistributionEnergy <- function(values, targets, weights) {
    .Call(`_EmpiricalPatternR_calcDistributionEnergy`, values, targets, weights)
}

calcCanopyCoverIndexedCpp <- function(x, y, crown_radius, plot_size = 100.0, grid_res = 0.5) {
    .Call(`_EmpiricalPatternR_calcCanopyCoverIndexedCpp`, x, y, crown_radius, plot_size, grid_res)
}

calcEnergyComponentsCpp <- function(metrics, targets, weights, component_ids) {
    .Call(`_EmpiricalPatternR_calcEnergyComponentsCpp`, metrics, targets, weights, component_ids)
}

calcCanopyCoverParallel <- function(x, y, crown_radius, plot_size = 100.0, grid_res = 0.5, n_threads = 0L) {
    .Call(`_EmpiricalPatternR_calcCanopyCoverParallel`, x, y, crown_radius, plot_size, grid_res, n_threads)
}

calcNearestDistanceParallel <- function(x1, y1, x2, y2, n_threads = 0L) {
    .Call(`_EmpiricalPatternR_calcNearestDistanceParallel`, x1, y1, x2, y2, n_threads)
}

calcCrownRadiusParallel <- function(dbh, species_idx, params, n_threads = 0L) {
    .Call(`_EmpiricalPatternR_calcCrownRadiusParallel`, dbh, species_idx, params, n_threads)
}

calcHeightParallel <- function(dbh, species_idx, params, n_threads = 0L) {
    .Call(`_EmpiricalPatternR_calcHeightParallel`, dbh, species_idx, params, n_threads)
}

calcCrownBaseHeightParallel <- function(dbh, height, species_idx, params, n_threads = 0L) {
    .Call(`_EmpiricalPatternR_calcCrownBaseHeightParallel`, dbh, height, species_idx, params, n_threads)
}

calcCEParallel <- function(xmax, ymax, x, y, n_threads = 0L) {
    .Call(`_EmpiricalPatternR_calcCEParallel`, xmax, ymax, x, y, n_threads)
}

getOpenMPInfo <- function() {
    .Call(`_EmpiricalPatternR_getOpenMPInfo`)
}

calcCanopyCoverHybrid <- function(x, y, crown_radius, plot_size = 100.0, grid_res = 0.5, n_threads = 0L) {
    .Call(`_EmpiricalPatternR_calcCanopyCoverHybrid`, x, y, crown_radius, plot_size, grid_res, n_threads)
}

